import { Topic, TopicCategory, VisualizationType } from './types';

export const INITIAL_TOPICS: Topic[] = [
  // --- GENAI & NLP ---
  {
    id: 'nlp-core',
    title: 'NLP Fundamentals',
    category: TopicCategory.GENAI,
    shortDesc: 'Tokenization, Embeddings, RNNs/LSTMs, and Attention.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'bert-encoding',
    title: 'BERT & Prompting',
    category: TopicCategory.GENAI,
    shortDesc: 'Encodings, Transformers, One-shot & Two-shot learning.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'rag-arch',
    title: 'RAG Architecture',
    category: TopicCategory.GENAI,
    shortDesc: 'Retrieval-Augmented Generation for grounded AI systems.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'fine-tuning',
    title: 'Fine-Tuning & PEFT',
    category: TopicCategory.GENAI,
    shortDesc: 'Adapting LLMs: LoRA, QLoRA, and full fine-tuning strategies.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'moe-models',
    title: 'Mixture of Experts (MoE)',
    category: TopicCategory.GENAI,
    shortDesc: 'Sparse gating networks and scaling efficiency.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'autoencoders',
    title: 'Autoencoders & VAEs',
    category: TopicCategory.GENAI,
    shortDesc: 'Latent space compression and generative modeling.',
    visualizationType: VisualizationType.NONE,
  },

  // --- DATA ENGINEERING & CLOUD ---
  {
    id: 'sql-adv',
    title: 'Advanced SQL',
    category: TopicCategory.DE,
    shortDesc: 'Window functions, CTEs, Query Optimization, and Indexing.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'data-eng',
    title: 'Data Engineering Core',
    category: TopicCategory.DE,
    shortDesc: 'ETL vs ELT, Batch vs Streaming, and Lambda Architecture.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'pipelines',
    title: 'Data Pipelines (Airflow)',
    category: TopicCategory.DE,
    shortDesc: 'Orchestration, DAGs, Backfills, and Dependency Management.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'lakehouse',
    title: 'Data Lakehouse',
    category: TopicCategory.DE,
    shortDesc: 'Unifying Warehouses and Lakes: Delta Lake, Iceberg, Hudi.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'data-gov',
    title: 'Data Governance',
    category: TopicCategory.DE,
    shortDesc: 'Data Quality, Lineage, Cataloging (Amundsen), and GDPR.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'cloud-eng',
    title: 'Cloud Engineering',
    category: TopicCategory.DE,
    shortDesc: 'IaC (Terraform), CI/CD, and Containerization (K8s).',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'aws-services',
    title: 'AWS Cloud-Native',
    category: TopicCategory.DE,
    shortDesc: 'Glue, Redshift, Kinesis, Lambda, and SageMaker patterns.',
    visualizationType: VisualizationType.NONE,
  },

  // --- ML ---
  {
    id: 'lin-reg',
    title: 'Linear Regression',
    category: TopicCategory.ML,
    shortDesc: 'Fundamental supervised learning algorithm for regression.',
    visualizationType: VisualizationType.LINEAR_REGRESSION,
  },
  {
    id: 'logistic-reg',
    title: 'Logistic Regression',
    category: TopicCategory.ML,
    shortDesc: 'Probabilistic classification and decision boundaries.',
    visualizationType: VisualizationType.LOGISTIC_REGRESSION,
  },
  {
    id: 'k-means',
    title: 'K-Means Clustering',
    category: TopicCategory.ML,
    shortDesc: 'Unsupervised partition-based clustering algorithm.',
    visualizationType: VisualizationType.K_MEANS,
  },
  {
    id: 'tree-ensembles',
    title: 'Random Forest & Boosting',
    category: TopicCategory.ML,
    shortDesc: 'Ensemble methods: Bagging vs. Boosting (XGBoost/LightGBM).',
    visualizationType: VisualizationType.TREE_ENSEMBLES,
  },
  {
    id: 'gradient-descent',
    title: 'Gradient Descent',
    category: TopicCategory.ML,
    shortDesc: 'Optimization algorithm for minimizing the cost function.',
    visualizationType: VisualizationType.GRADIENT_DESCENT,
  },
  {
    id: 'backprop',
    title: 'Backpropagation',
    category: TopicCategory.ML,
    shortDesc: 'The chain rule applied to neural network training.',
    visualizationType: VisualizationType.BACKPROPAGATION,
  },
  {
    id: 'metrics',
    title: 'Evaluation Metrics',
    category: TopicCategory.ML,
    shortDesc: 'Precision, Recall, F1, ROC-AUC, and business alignment.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'regularization',
    title: 'Overfitting & Regularization',
    category: TopicCategory.ML,
    shortDesc: 'L1 (Lasso), L2 (Ridge), Dropout, and Early Stopping.',
    visualizationType: VisualizationType.REGULARIZATION,
  },
  {
    id: 'feature-eng',
    title: 'Feature Engineering',
    category: TopicCategory.ML,
    shortDesc: 'Target encoding, Cyclic features, and Handling High Cardinality.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'pca',
    title: 'Principal Component Analysis',
    category: TopicCategory.ML,
    shortDesc: 'Dimensionality reduction via eigendecomposition.',
    visualizationType: VisualizationType.PCA,
  },
  {
    id: 'svm',
    title: 'Support Vector Machines',
    category: TopicCategory.ML,
    shortDesc: 'Finding the optimal hyperplane for classification.',
    visualizationType: VisualizationType.SVM,
  },
  {
    id: 'cv-split',
    title: 'Cross-Validation Strategy',
    category: TopicCategory.ML,
    shortDesc: 'K-Fold, Stratified, and Time-Series Splitting.',
    visualizationType: VisualizationType.NONE,
  },

  // --- STATS ---
  {
    id: 'norm-dist',
    title: 'Normal Distribution & CLT',
    category: TopicCategory.STATS,
    shortDesc: 'The foundation of parametric statistics and hypothesis testing.',
    visualizationType: VisualizationType.NORMAL_DISTRIBUTION,
  },
  {
    id: 'bayes-inf',
    title: 'Bayesian Inference',
    category: TopicCategory.STATS,
    shortDesc: 'Updating probabilities as new evidence becomes available.',
    visualizationType: VisualizationType.BAYESIAN,
  },
  {
    id: 'p-value',
    title: 'Hypothesis Testing',
    category: TopicCategory.STATS,
    shortDesc: 'P-values, Confidence Intervals, and Type I/II Errors.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'bias-variance',
    title: 'Bias-Variance Tradeoff',
    category: TopicCategory.STATS,
    shortDesc: 'Balancing model complexity and generalization error.',
    visualizationType: VisualizationType.BIAS_VARIANCE,
  },
  {
    id: 'distributions',
    title: 'Probability Distributions',
    category: TopicCategory.STATS,
    shortDesc: 'Binomial, Poisson, Exponential and their applications.',
    visualizationType: VisualizationType.PROB_DISTRIBUTIONS,
  },

  // --- PYTHON ---
  {
    id: 'sorting',
    title: 'Algorithmic Efficiency',
    category: TopicCategory.PYTHON,
    shortDesc: 'Big O notation, sorting, and search algorithms.',
    visualizationType: VisualizationType.SORTING,
  },
  {
    id: 'pandas-adv',
    title: 'Advanced Pandas',
    category: TopicCategory.PYTHON,
    shortDesc: 'Groupby, Merge, Reshaping, and Vectorized Operations.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'numpy-broadcasting',
    title: 'Numpy Broadcasting',
    category: TopicCategory.PYTHON,
    shortDesc: 'Understanding array shapes and implicit expansion.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'clean-code',
    title: 'Clean Code & Debugging',
    category: TopicCategory.PYTHON,
    shortDesc: 'Functions, Docstrings, Edge cases, and defensive programming.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'graph-algo',
    title: 'Graph Algorithms',
    category: TopicCategory.PYTHON,
    shortDesc: 'BFS, DFS, Dijkstra, and network analysis.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'dynamic-prog',
    title: 'Dynamic Programming',
    category: TopicCategory.PYTHON,
    shortDesc: 'Solving complex problems by breaking them into sub-problems.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'generators',
    title: 'Generators & Iterators',
    category: TopicCategory.PYTHON,
    shortDesc: 'Memory efficient iteration patterns in Python.',
    visualizationType: VisualizationType.NONE,
  },

  // --- MLOPS ---
  {
    id: 'deployment',
    title: 'Model Deployment',
    category: TopicCategory.MLOPS,
    shortDesc: 'Serving models via REST APIs, Docker containers.',
    visualizationType: VisualizationType.NONE,
  },
  {
    id: 'monitoring',
    title: 'Monitoring & Drift',
    category: TopicCategory.MLOPS,
    shortDesc: 'Detecting Training-Serving skew and Data Drift.',
    visualizationType: VisualizationType.NONE,
  },
];